# Generated by Django 6.0.3 on 2026-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=150)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('union_libre', 'Unión Libre'), ('viudo', 'Viudo')], max_length=20)),
                ('fecha_matrimonio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
