# Generated by Django 6.0.3 on 2026-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_educacion_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='empleado_recomendador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
